name: deploy
on:
  push:
    branches: [ master ]
jobs:  
  deploy-nest:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer o backup do arquivo .env
        uses: joaohcrangel/github-action-ssh@release
        with:
          command: cd /var/www/empreeduca-nest-js && sudo cp .env ../.env
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY}}

      - name: Baixar alterações do GitHub
        uses: joaohcrangel/github-action-ssh@release
        with:
          command: cd /var/www/empreeduca-nest-js && sudo npm run git
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY}}

      - name: Instalar módulos NPM
        uses: joaohcrangel/github-action-ssh@release
        with:
          command: cd /var/www/empreeduca-nest-js && sudo npm install
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY}}

      - name: Conferir se há atualizações no Banco de Dados
        uses: joaohcrangel/github-action-ssh@release
        with:
          command: cd /var/www/empreeduca-nest-js && sudo npm run migrate:up
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY}}

      - name: Realizar o build
        uses: joaohcrangel/github-action-ssh@release
        with:
          command: cd /var/www/empreeduca-nest-js && sudo npm run build
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY}}

      - name: Reiniciar o pm2
        uses: joaohcrangel/github-action-ssh@release
        with:
          command: cd /var/www/empreeduca-nest-js && pm2 restart nestjs
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_KEY}}